CREATE TABLE baseball.player_master (
  player_id INT AUTO_INCREMENT,
  fname VARCHAR(64) NOT NULL,
  lname VARCHAR(64) NOT NULL,
  position CHAR(3) NOT NULL,
  throw_hand CHAR(1),
  hit_hand CHAR(1),
  age TINYINT,
  start_year INT,
  fin_year INT,
  team_id CHAR(2) NOT NULL,
  regist_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (player_id)
);

CREATE TABLE baseball.starting_from_yahoo (
  game_id INT NOT NULL,
  team_id CHAR(2) NOT NULL,
  player_id_1 INT,
  position_1 CHAR(1),
  player_id_2 INT,
  position_2 CHAR(1),
  player_id_3 INT,
  position_3 CHAR(1),
  player_id_4 INT,
  position_4 CHAR(1),
  player_id_5 INT,
  position_5 CHAR(1),
  player_id_6 INT,
  position_6 CHAR(1),
  player_id_7 INT,
  position_7 CHAR(1),
  player_id_8 INT,
  position_8 CHAR(1),
  player_id_9 INT,
  position_9 CHAR(1),
  game_date CHAR(8),
  regist_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (game_id, team_id),
  CONSTRAINT fk_starting_from_yahoo_player_id_1 FOREIGN KEY (player_id_1) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_starting_from_yahoo_player_id_2 FOREIGN KEY (player_id_2) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_starting_from_yahoo_player_id_3 FOREIGN KEY (player_id_3) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_starting_from_yahoo_player_id_4 FOREIGN KEY (player_id_4) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_starting_from_yahoo_player_id_5 FOREIGN KEY (player_id_5) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_starting_from_yahoo_player_id_6 FOREIGN KEY (player_id_6) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_starting_from_yahoo_player_id_7 FOREIGN KEY (player_id_7) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_starting_from_yahoo_player_id_8 FOREIGN KEY (player_id_8) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_starting_from_yahoo_player_id_9 FOREIGN KEY (player_id_9) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE baseball.predict_bat_order (
  user_id INT NOT NULL,
  game_date CHAR(8),
  team_id CHAR(2) NOT NULL,
  predict_score TINYINT,
  player_id_1 INT,
  position_1 CHAR(1),
  player_id_2 INT,
  position_2 CHAR(1),
  player_id_3 INT,
  position_3 CHAR(1),
  player_id_4 INT,
  position_4 CHAR(1),
  player_id_5 INT,
  position_5 CHAR(1),
  player_id_6 INT,
  position_6 CHAR(1),
  player_id_7 INT,
  position_7 CHAR(1),
  player_id_8 INT,
  position_8 CHAR(1),
  player_id_9 INT,
  position_9 CHAR(1),
  regist_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, team_id, game_date),
  CONSTRAINT fk_predict_bat_order_player_id_1 FOREIGN KEY (player_id_1) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_predict_bat_order_player_id_2 FOREIGN KEY (player_id_2) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_predict_bat_order_player_id_3 FOREIGN KEY (player_id_3) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_predict_bat_order_player_id_4 FOREIGN KEY (player_id_4) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_predict_bat_order_player_id_5 FOREIGN KEY (player_id_5) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_predict_bat_order_player_id_6 FOREIGN KEY (player_id_6) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_predict_bat_order_player_id_7 FOREIGN KEY (player_id_7) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_predict_bat_order_player_id_8 FOREIGN KEY (player_id_8) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_predict_bat_order_player_id_9 FOREIGN KEY (player_id_9) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE baseball.pitcher_from_npb_official (
  player_id INT NOT NULL,
  year CHAR(4) NOT NULL,
  games TINYINT NOT NULL,
  win_num TINYINT NOT NULL,
  lose_num TINYINT NOT NULL,
  save_num TINYINT NOT NULL,
  hold TINYINT NOT NULL,
  hold_point TINYINT NOT NULL,
  complete_game TINYINT NOT NULL,
  whitewash_win_num TINYINT NOT NULL,
  no_walk TINYINT NOT NULL,
  win_rate FLOAT NOT NULL,
  against_batters INT NOT NULL,
  innings FLOAT NOT NULL,
  hits INT NOT NULL,
  homeruns TINYINT NOT NULL,
  fourball INT NOT NULL,
  got_walked TINYINT NOT NULL,
  dead_ball TINYINT NOT NULL,
  wild_pitch TINYINT NOT NULL,
  bork TINYINT NOT NULL,
  kk INT NOT NULL,
  allowed_runs INT NOT NULL,
  earned_run_average FLOAT NOT NULL,
  regist_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (player_id, year),
  CONSTRAINT fk_pitcher_from_npb_official_player_id FOREIGN KEY (player_id) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE baseball.pitcher_from_npb_official_2024 (
  player_id INT NOT NULL,
  year CHAR(4) NOT NULL,
  games TINYINT NOT NULL,
  win_num TINYINT NOT NULL,
  lose_num TINYINT NOT NULL,
  save_num TINYINT NOT NULL,
  hold TINYINT NOT NULL,
  hold_point TINYINT NOT NULL,
  complete_game TINYINT NOT NULL,
  whitewash_win_num TINYINT NOT NULL,
  no_walk TINYINT NOT NULL,
  win_rate FLOAT NOT NULL,
  against_batters INT NOT NULL,
  innings FLOAT NOT NULL,
  hits INT NOT NULL,
  homeruns TINYINT NOT NULL,
  fourball INT NOT NULL,
  got_walked TINYINT NOT NULL,
  dead_ball TINYINT NOT NULL,
  wild_pitch TINYINT NOT NULL,
  bork TINYINT NOT NULL,
  kk INT NOT NULL,
  allowed_runs INT NOT NULL,
  earned_run_average FLOAT NOT NULL,
  regist_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (player_id),
  CONSTRAINT fk_pitcher_from_npb_official_2024_player_id FOREIGN KEY (player_id) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE baseball.hitter_from_npb_official_2024 (
  player_id INT NOT NULL,
  year CHAR(4) NOT NULL,
  games TINYINT NOT NULL,
  plate_appearance INT NOT NULL,
  at_bat INT NOT NULL,
  score INT NOT NULL,
  hit_num INT NOT NULL,
  double_num TINYINT NOT NULL,
  triple_num TINYINT NOT NULL,
  homerun_num TINYINT NOT NULL,
  total_bases INT NOT NULL,
  rbi INT NOT NULL,
  steal_success TINYINT NOT NULL,
  steal_failure TINYINT NOT NULL,
  bunt TINYINT NOT NULL,
  sacrifice_fly TINYINT NOT NULL,
  fourball INT NOT NULL,
  got_walked INT NOT NULL,
  dead_ball TINYINT NOT NULL,
  kk INT NOT NULL,
  double_play TINYINT NOT NULL,
  bat DECIMAL(5,4) NOT NULL,
  slu DECIMAL(5,4) NOT NULL,
  obp DECIMAL(5,4) NOT NULL,
  regist_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (player_id),
  CONSTRAINT fk_hitter_from_npb_official_2024_player_id FOREIGN KEY (player_id) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE baseball.hitter_from_npb_official (
  player_id INT NOT NULL,
  year CHAR(4) NOT NULL,
  games TINYINT NOT NULL,
  plate_appearance INT NOT NULL,
  at_bat INT NOT NULL,
  score INT NOT NULL,
  hit_num INT NOT NULL,
  double_num TINYINT NOT NULL,
  triple_num TINYINT NOT NULL,
  homerun_num TINYINT NOT NULL,
  total_bases INT NOT NULL,
  rbi INT NOT NULL,
  steal_success TINYINT NOT NULL,
  steal_failure TINYINT NOT NULL,
  bunt TINYINT NOT NULL,
  sacrifice_fly TINYINT NOT NULL,
  fourball INT NOT NULL,
  got_walked INT NOT NULL,
  dead_ball TINYINT NOT NULL,
  kk INT NOT NULL,
  double_play TINYINT NOT NULL,
  bat DECIMAL(5,4) NOT NULL,
  slu DECIMAL(5,4) NOT NULL,
  obp DECIMAL(5,4) NOT NULL,
  regist_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (player_id),
  CONSTRAINT fk_hitter_from_npb_official_2024_player_id FOREIGN KEY (player_id) REFERENCES player_master(player_id) ON UPDATE NO ACTION ON DELETE NO ACTION
 

