
--コメント付与
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'試合のID'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'starting_from_yahoo'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'game_id'
                                 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'チームID'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'starting_from_yahoo'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'team_id'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'試合日'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'starting_from_yahoo'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'game_date'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'登録日時'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'starting_from_yahoo'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'regist_date'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'更新日時'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'starting_from_yahoo'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'update_date'
                                
--コメント付与
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'登録者のID'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'predict_bat_order'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'user_id'
                                 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'チームID'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'predict_bat_order'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'team_id'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'試合日'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'predict_bat_order'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'game_date'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'登録日時'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'predict_bat_order'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'regist_date'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'更新日時'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'predict_bat_order'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'update_date'
                                
--コメント付与
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'選手ID'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo' 
                                ,@level1type=N'TABLE'
                                ,@level1name=N'player_master'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'player_id'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'名前（姓）'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'player_master'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'fname'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'名前（名）'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'player_master'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'lname'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'選手区分（ポジション）'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'player_master'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'position'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'投球の右左'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'player_master'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'throw_hand'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'打席の右左'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'player_master'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'hit_hand'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'年齢'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'player_master'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'age'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'プロ入り年度'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'player_master'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'start_year'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'所属チーム'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'player_master'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'team_id'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'状態（現役、引退、メジャー）'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'player_master'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'status'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'登録日時'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'player_master'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'regist_date'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'更新日時'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'player_master'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'update_date'
                                
--コメント付与
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'選手ID'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'player_id'
                                 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'データ年度'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'year'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'登板数'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'games'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'勝利'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'win_num'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'敗北'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'lose_num'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'セーブ'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'save_num'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'ホールド'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'hold'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'ホールドポイント'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'hold_point'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'完投'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'complete_game'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'完封勝'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'whitewash_win_num'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'無四球'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'no_walk'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'勝率'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'win_rate'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'打者'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'against_batters'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'投球回'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'innings'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'安打'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'hits'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'本塁打'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'homeruns'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'四球'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'fourball'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'故意四球'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'got_walked'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'死球'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'dead_ball'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'三振'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'kk'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'暴投'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'wild_pitch'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'ボーク'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'bork'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'失点'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'allowed_runs'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'防御率'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'earned_run_average'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'登録日時'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'regist_date'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'更新日時'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'update_date'
--コメント付与
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'選手ID'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'player_id'
                                 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'データ年度'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'year'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'登板数'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'games'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'勝利'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'win_num'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'敗北'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'lose_num'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'セーブ'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'save_num'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'ホールド'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'hold'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'ホールドポイント'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'hold_point'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'完投'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'complete_game'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'完封勝'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'whitewash_win_num'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'無四球'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'no_walk'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'勝率'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'win_rate'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'打者'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'against_batters'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'投球回'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'innings'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'安打'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'hits'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'本塁打'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'homeruns'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'四球'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'fourball'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'故意四球'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'got_walked'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'死球'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'dead_ball'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'三振'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'kk'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'暴投'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'wild_pitch'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'ボーク'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'bork'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'失点'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'allowed_runs'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'防御率'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'earned_run_average'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'登録日時'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'regist_date'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'更新日時'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'pitcher_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'update_date'
                                
--コメント付与
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'選手ID'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'player_id'
                                 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'データ年度'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'year'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'試合数'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'games'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'打席'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'plate_appearance'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'打数'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'at_bat'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'得点'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'score'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'安打数'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'hit_num'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'二塁打'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'double_num'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'三塁打'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'triple_num'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'本塁打'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'homerun_num'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'塁打'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'total_bases'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'打点'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'rbi'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'盗塁数'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'steal_success'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'盗塁失敗'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'steal_failure'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'犠打'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'bunt'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'犠飛 '
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'sacrifice_fly'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'四球'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'fourball'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'故意四球'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'got_walked'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'死球'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'dead_ball'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'三振'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'kk'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'併殺打'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'double_play'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'打率'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'bat'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'長打率'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'slu'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'出塁率'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'obp'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'登録日時'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'regist_date'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'更新日時'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'update_date'

--コメント付与
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'選手ID'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'player_id'
                                 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'データ年度'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'year'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'試合数'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'games'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'打席'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'plate_appearance'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'打数'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'at_bat'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'得点'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'score'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'安打数'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'hit_num'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'二塁打'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'double_num'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'三塁打'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'triple_num'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'本塁打'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'homerun_num'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'塁打'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'total_bases'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'打点'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'rbi'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'盗塁数'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'steal_success'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'盗塁失敗'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'steal_failure'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'犠打'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'bunt'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'犠飛 '
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'sacrifice_fly'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'四球'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'fourball'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'故意四球'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'got_walked'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'死球'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'dead_ball'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'三振'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'kk'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'併殺打'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'double_play'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'打率'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'bat'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'長打率'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'slu'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'出塁率'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'obp'

EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'登録日時'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'regist_date'
 
EXEC sys.sp_addextendedproperty  @name=N'MS_Description'
                                ,@value=N'更新日時'
                                ,@level0type=N'SCHEMA'
                                ,@level0name=N'dbo'
                                ,@level1type=N'TABLE'
                                ,@level1name=N'hitter_from_npb_official_2024'
                                ,@level2type=N'COLUMN'
                                ,@level2name=N'update_date'
                                